# -*- mode: ruby -*-
# vi: set ft=ruby :



Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"
  config.vm.provision "shell" , path: "docker_install.sh", privileged:true
  config.vm.provision "shell" , path: "gcloud_sdk_install.sh", privileged:true
  config.vm.provision "shell" , path: "kubectl_install.sh", privileged:true

    config.vm.define "gce-client" do |client|
      client.vm.network "public_network", ip: "192.168.0.200"
      client.vm.hostname = "gce-client"
      client.vm.provider "virtualbox" do |vb|
       vb.memory = "4096"
       vb.cpus = 2
      end
    end
     
  
end


