# -*- mode: ruby -*-
# vi: set ft=ruby :



Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"
  config.vm.provision "shell" , path: "install.sh", privileged:false
  config.vm.provision "shell" , path: "k8s_repo.sh", privileged:true

      config.vm.define "k8s-server" do |server|
      server.vm.network "public_network", ip: "192.168.0.100"
      server.vm.hostname = "k8s-server"
      server.vm.provider "virtualbox" do |vb|
       vb.memory = "2048"
       vb.cpus = 2
      end
	end
      
  
end


