# -*- mode: ruby -*-
# vi: set ft=ruby :

K8S_MINION_COUNT = 3

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"
  config.vm.provision "shell" , path: "install.sh", privileged:false

  K8S_MINION_COUNT.times do |i|
    config.vm.define "minion#{i+1}" do |minion|
      minion.vm.network "public_network", ip: "192.168.0.#{i+1}"
      minion.vm.hostname = "minion#{i+1}"
      minion.vm.provider "virtualbox" do |vb|
       vb.memory = "2048"
       vb.cpus = 2
      end
	end
      
  end
end


